"""Use-cases and session state for the WoodCAM vector editor."""

from .editor_controller import CommandExecutionCancelled, EditorController, EditorMode
from .selection import SelectionModel
from .snapping import SnapCandidate, SnapEngine, SnapKind, SnapSettings
from .layers import (
    AddLayerCommand,
    SetActiveLayerCommand,
    UpdateLayerCommand,
    UpdateLayersCommand,
)
from .pieces import (
    ROTATION_MODES,
    UpdatePieceMetadataCommand,
    nesting_rotation_angles,
    piece_rotation_mode,
)
from .import_batches import prepare_import_batch
from .common_line import (
    CommonLineCutPath,
    CommonLineCutTrail,
    CommonLineContour,
    CommonLineIssue,
    CommonLineIssueCode,
    CommonLinePlan,
    CommonLinePlanningError,
    CommonLineSegment,
    build_common_line_cut_paths,
    build_common_line_cut_trails,
    plan_common_line_cut,
)
from .global_cut_plan import (
    CutDepthStrategy,
    CutOperation,
    CutPhase,
    CutRouteMetrics,
    GlobalCutPlan,
    GlobalCutPlanError,
    GlobalCutTrail,
    LooseWasteFixationMode,
    OwnedContour,
    PhysicalCutSegment,
    PhysicalSegmentKind,
    PieceMetrics,
    RetentionGraph,
    RetentionRules,
    RetentionTab,
    ScrewAnchor,
    SegmentDepthCoverage,
    StabilityReport,
    TabReleaseMode,
    TabReleaseOperation,
    TabRetentionKind,
    TrailRoute,
    WasteRegion,
    build_global_cut_plan,
    optimize_fast_trails,
)

__all__ = [
    "EditorController",
    "EditorMode",
    "CommandExecutionCancelled",
    "SelectionModel",
    "SnapCandidate",
    "SnapEngine",
    "SnapKind",
    "SnapSettings",
    "AddLayerCommand",
    "SetActiveLayerCommand",
    "UpdateLayerCommand",
    "UpdateLayersCommand",
    "ROTATION_MODES",
    "UpdatePieceMetadataCommand",
    "piece_rotation_mode",
    "nesting_rotation_angles",
    "prepare_import_batch",
    "CommonLineCutPath",
    "CommonLineCutTrail",
    "CommonLineContour",
    "CommonLineIssue",
    "CommonLineIssueCode",
    "CommonLinePlan",
    "CommonLinePlanningError",
    "CommonLineSegment",
    "build_common_line_cut_paths",
    "build_common_line_cut_trails",
    "plan_common_line_cut",
    "CutDepthStrategy",
    "CutOperation",
    "CutPhase",
    "CutRouteMetrics",
    "GlobalCutPlan",
    "GlobalCutPlanError",
    "GlobalCutTrail",
    "LooseWasteFixationMode",
    "OwnedContour",
    "PhysicalCutSegment",
    "PhysicalSegmentKind",
    "PieceMetrics",
    "RetentionGraph",
    "RetentionRules",
    "RetentionTab",
    "ScrewAnchor",
    "SegmentDepthCoverage",
    "StabilityReport",
    "TabReleaseMode",
    "TabReleaseOperation",
    "TabRetentionKind",
    "TrailRoute",
    "WasteRegion",
    "build_global_cut_plan",
    "optimize_fast_trails",
]
